run_threads:
	gcc threads.c -o threads -lpthread
	./threads

run_omp_hw:
	gcc -fopenmp omp_helloWorld.c -o omp_helloWorld  
	./omp_helloWorld

run_omp_pi:
	gcc -fopenmp omp_pi.c -o omp_pi
	./omp_pi

clean:
	rm -f threads omp_helloWorld omp_pi